name: Docker
on:
  # Run tests for any PRs.
  pull_request:

permissions: read-all

env:
  IMAGE_NAME: packagefeeds

jobs:
  build-image:
    name: Build  image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Test build on x86
        id: docker_build
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false # Only attempt to build, to verify the Dockerfile is working
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
